const os=require('os')
console.log(os.type())
console.log(os.version())
console.log(os.freemem())
console.log(os.cpus())
console.log(__dirname)
console.log(__filename)
console.log(os.arch())
console.log(os.platform(),os.hostname())